"""user_comments_field

Revision ID: 65c978a6eb58
Revises: 8e4b8c294821
Create Date: 2024-08-15 17:14:25.874018

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65c978a6eb58"
down_revision: Union[str, None] = "8e4b8c294821"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "good",
        "rate_sum",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=3, scale=2),
        existing_nullable=False,
    )
    op.add_column(
        "user", sa.Column("comments", sa.ARRAY(sa.JSON()), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "comments")
    op.alter_column(
        "good",
        "rate_sum",
        existing_type=sa.Numeric(precision=3, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
