"""fields_to_count_rate

Revision ID: 8e4b8c294821
Revises: a652d1fa9c7c
Create Date: 2024-08-15 15:31:11.371890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e4b8c294821"
down_revision: Union[str, None] = "a652d1fa9c7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("good", sa.Column("rate_cnt", sa.Integer(), nullable=False))
    op.add_column("good", sa.Column("rate_sum", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("good", "rate_sum")
    op.drop_column("good", "rate_cnt")
    # ### end Alembic commands ###
