"""add seller's data

Revision ID: a652d1fa9c7c
Revises: 19121ccae367
Create Date: 2024-08-15 11:42:14.449134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a652d1fa9c7c"
down_revision: Union[str, None] = "19121ccae367"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("seller_data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "seller_data")
    # ### end Alembic commands ###
