"""add_rated_by

Revision ID: b1a53927725f
Revises: 65c978a6eb58
Create Date: 2024-08-15 18:53:34.507892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1a53927725f"
down_revision: Union[str, None] = "65c978a6eb58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "good", sa.Column("rated_by", sa.ARRAY(sa.Integer()), nullable=[False])
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("good", "rated_by")
    # ### end Alembic commands ###
