"""made_not_nullable

Revision ID: f794ea723842
Revises: b1a53927725f
Create Date: 2024-08-26 15:05:02.980493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f794ea723842"
down_revision: Union[str, None] = "b1a53927725f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "good",
        "rated_by",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        nullable=[False],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "good",
        "rated_by",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        nullable=True,
    )
    # ### end Alembic commands ###
