services:

  db:
    image: postgres:16
    container_name: db_shop
    env_file:
      - .env_non_dev
    volumes:
      - online_shop_db:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_shop

  app:
    build:
      context: .
    env_file:
      - .env_non_dev
    container_name: app_shop
    command: sh -c "alembic upgrade head & cd src && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 9999:8000
    depends_on:
      - redis
      - db

  celery:
    build:
      context: .
    env_file:
      - .env_non_dev
    container_name: celery_shop
    command: celery --app=src.tasks.email_task:celery worker -l INFO
    depends_on:
      - redis

  flower:
    container_name: flower_shop
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      - redis

volumes:
  online_shop_db:
